import { Box } from "@chakra-ui/react";
import Head from "next/head";
import { useEffect } from "react";
import useFetch from "../hooks/useFetch";
import Header from "../components/Header/Header";
import Body from "../components/Body/Body";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Body />
    </Box>
  );
}
